name: Sensible Web Development
markdown: redcarpet
highlighter: pygments
baseurl: ''
tracking_id: UA-40241848-1
tracking_property: qrohlf.com
github_repo: qrohlf/sensible-web-development
exclude: [compass.rb, config.ru, Gemfile, Gemfile.lock, Procfile, Rakefile, README.md, sass, unicorn.rb, vendor]
collections: 
  chapters:
    output: true
